[profile.default]
ffi = false
fuzz_runs = 256
optimizer = true
viaIR = true
optimizer_runs = 10000
remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts",
  "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
  "@uniswap/v2-periphery/=lib/v2-periphery",
]
verbosity = 1
fs_permissions = [{ access = "read-write", path = "./img"}]
